### ISSUE TITLE
bug 模拟器房间的每秒tick数显示一直是1

### ISSUE THREAD

**Issue by kamust** [HoPGoldy/screeps-chinese-pack#9]
1.如题
2.我建议把教程结束时的stay翻译为"留在这里"

**Comment by LOSKIw** [comment]
了解

**Comment by HoPGoldy** [comment]
翻译已更新，另外未发现模拟器房间的每秒 tick 数显示一直是 1 的问题，请进行确认，如有问题请 reopen 本 issue。
